_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 89
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 89
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.9
            "8":
                - 3
                - 8
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 8
lr:
    value: 0.0001
num_epochs:
    value: 5
weight_decay:
    value: 1e-05
